version: "3.3"
volumes:
  db:
    driver:
      local
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: what-to-do_image
    container_name: What-To-Do
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - todoApp-network

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: todoApp-db
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_PASSWORD: pass
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    networks:
      - todoApp-network

  nginx:
    image: nginx:alpine
    container_name: todoApp-nginx
    restart: unless-stopped
    ports:
      - 443:80
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - todoApp-network

networks:
  todoApp-network:
    driver: bridge
